In [1]:
import pandas as pd

In [2]:
df_02 = pd.read_csv(
    "C:/Users/user/team01/부산항만공사_외내항컨테이너통합집계정보_20241231.csv",
    encoding="cp949"
)
df_02.head(3)

,연도,월,분기,청코드,내외항구분,수출입구분명,시설코드,시설명,부두구분명,아외국구분,적공구분,컨테이너수(10피트),컨테이너수(20피트),컨테이너수(40피트),컨테이너수(기타),전체개수,전체물동량
0,2024,3,1,신항,외항,수입,6,신항 W 정박지,일반부두,외국선,적컨,0,3,8,0,11,19.0
1,2024,4,2,신항,외항,수입,6,신항 W 정박지,일반부두,아국선,적컨,0,9,3,0,12,15.0
2,2024,11,4,신항,외항,수입환적,7,신항 U 정박지,일반부두,아국선,공컨,0,1,0,0,1,1.0

In [4]:
df_con = df_02.copy()

In [10]:
df_con_copy = df_con[["연도","분기","내외항구분","수출입구분명","전체물동량"]].copy()

In [12]:
df_con_copy

        연도  분기 내외항구분 수출입구분명     전체물동량
0     2024   1    외항     수입     19.00
1     2024   2    외항     수입     15.00
2     2024   4    외항   수입환적      1.00
3     2024   4    외항     수입     61.00
4     2024   4    외항   수입환적    231.00
...    ...  ..   ...    ...       ...
2404  2024   3    외항   수입환적  21637.00
2405  2024   3    외항     수출  20599.50
2406  2024   3    외항     수입  22324.00
2407  2024   4    외항     수출   6561.75
2408  2024   4    외항     수입  11877.00

[2409 rows x 5 columns]